[files]
extend-exclude = [
    ".git/",
    "source/",
    "wordpress-stubs.php",
]
ignore-hidden = false

[default.extend-identifiers]
"get-post-stati" = "get-post-stati"
Automattic = "Automattic"
get_post_stati = "get_post_stati"
Github = "GitHub"
Woocommerce = "WooCommerce"
Wordpress = "WordPress"
